[package]
name = "test_game"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 1

[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12.1"
